---
dspace_version: dspace-7.0-beta4
dspace_installation_dir: "{{ ansible_env.HOME }}" # installation directory on the target system

dspace_host: 192.168.98.111

dspace_admin_mail: test@test.edu
dspace_admin_password: admin

dspace_import_AIP_test_data: true

docker_users:
  - vagrant
