---
- hosts: all
  vars_files:
      - vars/main.yml
  

  
  collections:
  - community.general
  - community.postgresql
  - ansible.posix

  roles:
    - role: geerlingguy.postgresql
      become: true
    - ui
    - java
    - ant
    - solr
    - tomcat
    - postgreSQL
    - maven
    - dspace
  
  tasks:
  
  - shell: ps -eo pcpu,user,args | sort -r -k1 | head -n5
    register: ps

  - debug: var=ps.stdout_lines