---
- name: Install PostgreSQL server package
  become: yes
  package:
    name: [ postgresql, postgresql-contrib ]
    state: present

- name: configure postgres
  become: yes
  lineinfile:
    path: "{{ postgres_conf_dir }}/postgresql.conf"
    regex: "^#?{{ item.name }} ="
    line: "{{ item.name }} = '{{ item.value }}'"
    create: yes
    mode: "u=rw,go=r"
  loop:
    - name: listen_addresses
      value: "{{ postgres_listen_addresses }}"
  notify:
    - restart postgres

- name: create pg_hba.conf
  become: yes
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_conf_dir }}/pg_hba.conf"
    mode: "u=rw,g=r,o="
  notify:
    - restart postgres
